### ISSUE TITLE
Remove `Map` relationship mapping

### ISSUE THREAD

**Issue by fbiville** [neo4j-examples/sdn-migration#44]
As noted by @meistermeier yesterday, mapping to relationships was only possible with `Map` in SDN-RX, but that limitation has been removed in SDN 6.

**Comment by meistermeier** [comment]
I won't call it limitation. It is just not possible anymore to use the `Map` definition. Technical yes, but outcome 🤷‍♀️

**Comment by fbiville** [comment]
Oh ok, I misunderstood.
I thought that `Map` were the only legal Java type for mapping relationships in entities in SDN-RX but that they were still allowed in SDN 6.

Are you saying `Map` is not valid type for relationships in SDN 6 anymore?

**Comment by meistermeier** [comment]
The `Map` is now only for dynamic relationships. There can be also dynamically typed `RelationshipProperties` in there but this is another thing.
Simple speaking going from Neo4j-OGM's `RelationshipEntity` to `RelationshipProperties` reference the property scalar or in a `List`.
